
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
# clone_folder: c:\projects\myproject

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
    - Win64
    - Win32

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: appveyorTest.sln      # path to Visual Studio solution or project

after_build:
  - cd Release\%platform%
  - 7z a ..\..\dpps.%platform%.zip dpps.*.dll
  - 7z a ..\..\dpps.%platform%.zip dppsTest.exe
  - cd ..\..

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#       deploy configuration      #
#---------------------------------#

artifacts:
  - path: dpps.*.zip
    name: zipPack
    type: zip


deploy:
  provider: GitHub
  auth_token:
    secure: 1qhWE2Ysf6odyKU0+ZC5YEvtXrKTy6mNn2CidseBhTd4kIf3srH0d4raxYQI0Mtj # your encrypted token from GitHub
  artifact: zipPack
  on:
    branch: appveyor               # release from master branch only

