
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
# clone_folder: c:\projects\myproject

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
    - x64
    - x86

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: appveyorTest.sln      # path to Visual Studio solution or project

after-build:
    - ps: Compress-Archive .\x64\Release\dpps.*.dll -DestinationPath dpps.win64.zip
    - ps: Compress-Archive .\x64\Release\dppsTest.exe -DestinationPath dpps.win64.zip -Update
    - ps: Compress-Archive .\Release\dpps.*.dll -DestinationPath dpps.win32.zip
    - ps: Compress-Archive .\Release\dppsTest.exe -DestinationPath dpps.win32.zip -Update

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#       deploy configuration      #
#---------------------------------#

deploy:
  provider: GitHub
  auth_token:
    secure: 1qhWE2Ysf6odyKU0+ZC5YEvtXrKTy6mNn2CidseBhTd4kIf3srH0d4raxYQI0Mtj # your encrypted token from GitHub
  artifact: dpps.*.zip             # upload all NuGet packages to release assets
  on:
    branch: appveyor               # release from master branch only


#---------------------------------#
#         notifications           #
#---------------------------------#

# notifications:

#   # Email
#   - provider: Email
#     to:
#       - user1@email.com
#       - user2@email.com
#     subject: 'Build {{status}}'                  # optional
#     message: "{{message}}, {{commitId}}, ..."    # optional
#     on_build_status_changed: true

